
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>   
  port: <%= ENV["POSTGRES_PORT"] %>
  host: <%= ENV["POSTGRES_HOST"] %>

test:
 <<: *default
 database: ams_test_db

production:
  primary: &primary_production
   <<: *default
   database: ams_production_db
   username: ams
   password: <%= ENV["AMS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: ams_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: ams_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: ams_production_cable
    migrations_paths: db/cable_migrate
